version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app
      - static_data:/vol/web

    expose:
      - "8000"

    env_file:
      - ./drm_backend/.env

    environment:
      - PROD=1
    depends_on:
      - db


#    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  nginx:
    restart: always

    build:
      context: ./nginx

    volumes:
    - static_data:/vol/web

    ports:
      - "8080:8080"

    depends_on:
      - web

volumes:
  static_data: