version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./drm_backend/.env
    expose:
      - "5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - static_data:/vol/web

    expose:
      - "8000"

    env_file:
      - ./drm_backend/.env

    environment:
      - PROD=1
    depends_on:
      - db

  nginx:
    restart: always

    build:
      context: ./nginx

    volumes:
    - static_data:/vol/web

    ports:
      - "8080:8080"

    depends_on:
      - web

volumes:
  static_data: