# Generated by Django 3.0.7 on 2020-09-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
