# Generated by Django 3.0.7 on 2020-09-09 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0002_auto_20200909_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 9, 7, 8, 27, 667296, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
