# Generated by Django 3.0.7 on 2020-09-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0003_auto_20200909_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='family_medical_history_complete',
        ),
    ]
